### PR TITLE
updated base_url with url filter

### PR DESCRIPTION
**Pull request by ZsharE**

### CODE REVIEW

**Comment by ThomasArdal** [comment]
I'm getting the following error when trying to run the project locally:

```
File "C:\elmah.io\elmah.io.documentation\mkdocs_bs4\main.html", line 26, in <module>
    <link rel="shortcut icon" href="{{ base_url|url }}/favicon.ico">
```

**Comment by ZsharE** [comment]
I don't have any errors. Maybe, consider update mkdocs ?
They have very poor documentation. 😞

**Comment by ThomasArdal** [comment]
Which version of MkDocs are you running?

**Comment by ZsharE** [comment]
mkdocs --version said version 1.0

**Comment by ThomasArdal** [comment]
Oh no. After upgrading to 1.0.1, I get the following warnings in the log:

```
WARNING -  Config value: 'theme_dir'. Warning: Unrecognised configuration name: theme_dir
WARNING -  Config value: 'pages'. Warning: The 'pages' configuration option has been deprecated and will be removed in a future release of MkDocs. Use 'nav' instead.
```

Can you find out how to make it work with the new version? :smile:

**Comment by ZsharE** [comment]
Go to mkdocs.yaml and configure this:

```
theme:
    name: null
    custom_dir: "mkdocs_bs4/"
```
Use 'nav' instead of 'pages'.

**Pull request merged**
