### PR TITLE
Task 311

### PR DESCRIPTION
**Pull request by ZsharE**
Added back-to-top button, installation auto-extend.
Updated year in footer.

### CODE REVIEW

**Comment by ThomasArdal** [comment]
@ZsharE I don't see the back to top button?

**Comment by ZsharE** [comment]
image

**Comment by ThomasArdal** [comment]
@ZsharE Ah, you're right. Mobile only ;)

Looks good.

**Comment by ThomasArdal** [comment]
It's live! 👍

**Pull request merged**
