### PR TITLE
New theme

### PR DESCRIPTION
**Pull request by ZsharE**
I added a new theme based on Bootstrap 4.
Enjoy !

### CODE REVIEW

**Comment by ThomasArdal** [comment]
Could you link to https://elmah.io/pricing/ from the sign up button in the footer.

**Comment by ThomasArdal** [comment]
The following links for policies (footer) changed since you started:

- https://elmah.io/legal/privacy-policy/
- https://elmah.io/legal/refund-policy/

**Comment by ZsharE** [comment]
Done.

**Comment by ThomasArdal** [comment]
You Rock!

**Pull request merged**
